sudo: required
services:
  - docker

before_install:
  - docker build -t kmlnuriyev/docker-react-app -f Dockerfile.dev .

script:
  - docker run kmlnuriyev/docker-react-app npm run test -- --watchAll=false

# To deploy to AWS-Elasticbeanstalk
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY #(will take from Travis environment variables)
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"