sudo: required
services:
  - docker

before_install:
  - docker build -t kmlnuriyev/docker-react-app -f Dockerfile.dev .

script:
  - docker run kmlnuriyev/docker-react-app npm run test -- --watchAll=false