version: '3.8'
services:
  web:
    # build: . -> this will try to find the Dockerfile and cannot find because we have Dockerfile.dev therefore ...
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app